import type { ErrorCode } from "#src/contracts/index.js";
import { ERROR_STATUS } from "#src/lib/errors.js";
import { FAILURE_INFO } from "#src/lib/modelFailures.js";

// The docs' errors page, generated from the error map (so a new code can't go undocumented): `pnpm docs:generate`.

/** What each error code means to a caller, and what to do about it. */
export const ERROR_DESCRIPTIONS: Readonly<Record<ErrorCode, string>> = {
  UNAUTHORIZED: "No valid API key or session token. Check the key; a revoked or expired key is refused the same way as an unknown one.",
  VALIDATION_FAILED: "The request isn't valid. `error` names the field and the problem; `details.fields` lists every field that failed.",
  NOT_FOUND: "It doesn't exist, or it isn't yours (the API never says which).",
  RUN_ACTIVE: "The chat already has a run in progress. Wait for it to end (or stop it), then send again.",
  RUN_NOT_RETRYABLE: "Only a chat's latest turn can be retried, and only if it failed or was stopped (the app's retry).",
  API_KEY_LIMIT_REACHED: "You already have the most active API keys allowed (10). Revoke one to create another.",
  IDEMPOTENCY_CONFLICT: "The `Idempotency-Key` was already used for a different request, or the first request with it is still being handled.",
  INSUFFICIENT_CREDITS: "Not enough credits for this. Nothing was charged.",
  PAYLOAD_TOO_LARGE: "The request body is over 1 MB.",
  RATE_LIMITED: "A limit was reached: your key's per-minute or daily limit, or the allowance for starting work. Wait for `Retry-After` seconds; `details` says which limit.",
  UPLOAD_LIMIT_REACHED: "The month's upload allowance is used up (the app's uploads). It resets on the 1st.",
  SERVICE_UNAVAILABLE: "Something the request needs is unavailable right now (for example the free model's daily limit, or a service that didn't answer). Try again later; `details` may say why.",
  INTERNAL_ERROR: "Something went wrong on our side. Try again, and quote the `traceId` if it keeps happening.",
};

/** Why a run failed, as `run.error.code` (GET /v1/runs/{runId}) and the `agent.failed` webhook give it. */
export const RUN_FAILURES: readonly { code: string; meaning: string }[] = [
  ...Object.values(FAILURE_INFO).map(({ code, message }) => ({ code, meaning: message })),
  { code: "WAITPOINT_EXPIRED", meaning: "Nobody answered the plan or spend approval within 30 minutes. Send a new message to continue." },
  { code: "INSUFFICIENT_CREDITS", meaning: "The credits ran out during the run. What it finished is kept." },
  { code: "AGENT_MAX_STEPS", meaning: "The agent reached its limit of steps (model calls) before finishing. What it did so far is kept." },
  { code: "AGENT_TIMEOUT", meaning: "The run took longer than its time limit." },
  { code: "AGENT_CRASHED", meaning: "The worker running it stopped unexpectedly." },
  { code: "AGENT_FAILED", meaning: "The worker reported the run as failed." },
  { code: "AGENT_ERROR", meaning: "The agent ran into an unexpected problem." },
  { code: "AGENT_NOT_STARTED", meaning: "No worker could start the run (the service may be down)." },
  { code: "AGENT_EXPIRED", meaning: "The run waited in the queue too long and was dropped." },
  { code: "DISPATCH_LOST", meaning: "The run was never handed to a worker." },
  { code: "RESULT_LOST", meaning: "The answer was generated but couldn't be saved." },
  { code: "CONTEXT_EMPTY", meaning: "The message the run was answering couldn't be found." },
];

const row = (...cells: string[]) => `| ${cells.join(" | ")} |`;

export function errorsPage(): string {
  const codes = (Object.entries(ERROR_STATUS) as [ErrorCode, number][]).sort(([a, x], [b, y]) => x - y || a.localeCompare(b));
  return [
    "---",
    'title: "Errors"',
    'description: "Every error code, its HTTP status, and what to do about it."',
    "---",
    "",
    "{/* Generated by `pnpm docs:generate` from the error map: edit src/openapi/errorsPage.ts, not this file. */}",
    "",
    "Every error has the same shape. `error` is safe to show to a user; `code` is stable, so branch on it.",
    "",
    "```json Error",
    JSON.stringify({ error: "That API key isn't valid. Check it, or create a new one.", code: "UNAUTHORIZED", traceId: "5787578d-cec2-41c2-b100-9dabf18a95c8" }, null, 2),
    "```",
    "",
    "`traceId` is also sent as the `x-trace-id` header of every response. Quote it when asking for help.",
    "",
    "## HTTP errors",
    "",
    row("Code", "Status", "Meaning"),
    row("---", "---", "---"),
    ...codes.map(([code, status]) => row(`\`${code}\``, String(status), ERROR_DESCRIPTIONS[code])),
    "",
    "## Why a run failed",
    "",
    "A run that fails is still answered `200` by `GET /v1/runs/{runId}`: its `status` is `failed` and `error` says why. The `agent.failed` webhook carries the same code (as `data.code`) and message.",
    "",
    row("Code", "Meaning"),
    row("---", "---"),
    ...RUN_FAILURES.map(({ code, meaning }) => row(`\`${code}\``, meaning)),
    "",
  ].join("\n");
}
